### ISSUE TITLE
Neither Windows App or Web App js are saving correctly, Windows App opens wrong file

### ISSUE THREAD

**Issue by CaverBruce** [rsevero/mapiah#6]
Acknowledge that Web app is/should be saving to downloads folder.
With 0.2.4 made some edits to the attached file, and clicked save (and 'save as' with Windows variant - 'save as' presented no dialog, appeared to replicate save - unverified).  

> [141c-TradePlan.txt](https://github.com/user-attachments/files/20741094/141c-TradePlan.txt)
> 
> This Therion drawing file seems to load in mapiah just fine.
> 
> [content snipped]
>
> On web version saving is actually a download. I would expect the updated file be available on your default download folder.
> 
> I just included the following explanation on TH2FileEditPageHelp with commit 2d2b343:
> 
> 
> ## Web releases
> 
> ### Save
> 
> Saving on web releases are actually download requests. In case you have your browser set to automatically download to a default download folder, please check there for the updated file after save.
>  

 _Originally posted by @rsevero in [#2](https://github.com/rsevero/mapiah/issues/2#issuecomment-2975907726)_

In both cases the file opened is not updated when saved.
With the web js version no file is updated or created as far as I can tell.  I checked my MS Edge downloads folder, and it is what I expected.

With Windows App no change to the file opened is made, as verified by the git repo not registering any change.  On searching around I found that it saves to C:\Users\Bruce\Documents.

Further, with the Windows App, when subsequently opening from my project folder D:\CaveSurvey\th_RiwakaCaveSystemData\th_RiuwakaCaveSystem\NgaruaArea\TradiesCave\... it ACTUALLY opens the file in C:\Users\Bruce\Documents.  Disconcerting!

At least the web app opens from the correct location each time (at least as far as my testing has gone so far).

PS: I had Mapiah 0.0.3 from 2022 installed on my machine.  I uninstalled that and deleted remnant files before installing 0.2.4 just now.

**Comment by rsevero** [comment]
With commit b0dfc3c I fixed the save issue in non web releases.

I can't see the problem in web releases, i.e., it saves just ok for me. On my debugging environment, it automatically creates a new file in the downloads folder.

In my regular browser, which is configured to always ask where to save downloaded files, I can choose the destination path and filename when saving.

I tested the web version on Edge and it worked as described above .

If you still sees a different behaviour, can you please send me a video showing the issue?

**Comment by CaverBruce** [comment]
With 0.2.5 Windows App, saving and opening behaviour is as expected and as documented (after adding an extra line to a scrap).   Yet to check web app...

**Comment by CaverBruce** [comment]
Webjs still fails silently when it comes to saving, with these settings in Edge.

![Image](https://github.com/user-attachments/assets/d00444b2-9f6d-4fe1-a6a0-849e040c13d7)

I turned on ask where to save.  No change.  Therefore I deduce something is failing before a save is attempted.

https://github.com/user-attachments/assets/02bbf21c-af07-43b6-9bea-8f3095e22893
I forgot to move the camera, but the last bit was me refreshing and checking the users' download and documents folders.  From previous attempts, there is no indication that anything is saved elsewhere (unless it is in a browser cache perhaps).

**Comment by rsevero** [comment]
Sorry for the delay, I was on the road coming back home from a cave trip.

There are no messages starting with _DEBUG (Mapiah)_?

**Comment by CaverBruce** [comment]
Nothing I could see. I'm away from my Windows devices for a few days, so further testing will be delayed.

**Comment by CaverBruce** [comment]
Browser right-click fix: I was going to mention that, so great.  Confirm it is fixed in Edge (but not in Brave - unsupported, so that is OK).

Web release: In general I have had very poor experiences with browser versions of software (MS Outlook, Word, Excel - disparate document rendering, behaviours and limited capability when compared with the application counterparts.  WTherion was going that way too) so I dislike them intently.  To the contrary Mapiah looks like it is bypassing those limitations (with the possible exception of saving to downloads folder.
So, I am going to come out in support of the Mapiah web browser platform.
Pros - 
1 for the existing user a quick way of trying the product/new version.  At Mapiah's current stage it is always the platform I try first.
2 a couple of days ago I introduced another caver to it and walked them through it.  If it were only available as an application we would not have bothered at all in the time available.  A web page has less impact on a potential user's machine than downloading potentially fringe software.  It can give confidence that, yes, I should download the app version, or no, it's not for me.
3 In a scenario where I am creating cave maps with Mapiah full time, and I take a vacation away from my usual devices and workstation, I can make minor edits to a cave project stored online from any (compatible) web browser (such as with collaborative version controlled projects).

Cons -
1 Saves to downloads - can be worked around in future?
2 Additional development overhead?

**Comment by rsevero** [comment]
> Web release: In general I have had very poor experiences with browser versions of software (MS Outlook, Word, Excel - disparate document rendering, behaviours and limited capability when compared with the application counterparts. WTherion was going that way too) so I dislike them intently. To the contrary Mapiah looks like it is bypassing those limitations (with the possible exception of saving to downloads folder. So, I am going to come out in support of the Mapiah web browser platform.

>Pros - 1 for the existing user a quick way of trying the product/new version. At Mapiah's current stage it is always the platform I try first.
> 2 a couple of days ago I introduced another caver to it and walked them through it. If it were only available as an application we would not have bothered at all in the time available. A web page has less impact on a potential user's machine than downloading potentially fringe software. It can give confidence that, yes, I should download the app version, or no, it's not for me.
> 3 In a scenario where I am creating cave maps with Mapiah full time, and I take a vacation away from my usual devices and workstation, I can make minor edits to a cave project stored online from any (compatible) web browser (such as with collaborative version controlled projects).

Great points. I am sold: I will keep the web release.

> Cons - 1 Saves to downloads - can be worked around in future?

I really believe so. We have to debug a little more to see whats happening.

Its really strange that no _DEBUG (Mapiah)_ messsge is presented to you. That would mean that the save process is failing by not even entering the save method which makes no sense. I bet we just have to better understand "Dev Tools" console on your machine.

> 2 Additional development overhead?

There is some but not much, its manageable for now. These last issues I solved were the ones that were bothering me a lot.

If we manage to fix the save issue for you, it will be perfect, i.e., it will have no web release specific issue.

**Comment by CaverBruce** [comment]
I meant to post this this morning.  From MS Edge...
![Image](https://github.com/user-attachments/assets/e97a5e9c-bba7-4411-ba93-68f039763613)
Since then I have noticed that I only get this (successful) response if I open, and without making changes, save.

If I make changes such as drawing a new line, then clicking the save button, it is silently ignored, just as it was with earlier versions.
Heading back to the console using version 0.2.6, I am now seeing the DEBUG messages.

![Image](https://github.com/user-attachments/assets/9a46a8cb-99b5-4c14-86b9-42e1bea28556)

Going one step at at time.
1. Open Mapiah js

![Image](https://github.com/user-attachments/assets/7701c00c-55c6-4a74-967c-9521c9eaaf11)
2. Open the file

![Image](https://github.com/user-attachments/assets/924dee77-92c1-46bb-ba21-b7d3316d5272)
3. Draw a line (no console messages added)
4. Click save (no error, no save - at least not to downloads or in the current 'users' folder).

![Image](https://github.com/user-attachments/assets/414e7c0d-d2c4-4037-aa09-a83d08c2236f)
